import datetime # Import Date-Time package
from langchain_core.callbacks import BaseCallbackHandler # Import base-class required to create a callback handler
from typing import Any, Dict, List # Import Type-Hints package
from langchain_core.outputs import LLMResult # Import class representing LLM response
from pathlib import Path # Import Path library

current_dir = Path(__file__).parent # Get current directory

ACTIVITY_LOG_FILE = current_dir.parent.parent / "activity.log" # Go two levels up the order to access the logging file

class CallBackHandler(BaseCallbackHandler): # Custom call-back handler that inherits from the imported base class
    def on_llm_start(self, serialized:Dict[str, Any], prompts:List[str], **kwargs:Any) -> Any: # Method/Hook triggered immediately before LLM starts executing
        with open(ACTIVITY_LOG_FILE, mode="a") as file: # Open the log file in append mode
            file.write(f"[{datetime.datetime.now()}] Final Prompt Sent to LLM: '{prompts[0]}'\n") # Write the final generated prompt passed to the LLM

    def on_llm_end(self, response:LLMResult,  **kwargs:Any) -> Any: # Method/Hook triggered immediately after the LLM generates a response
        with open(ACTIVITY_LOG_FILE, mode="a") as file: # Open the log file in append mode
            file.write(f"[{datetime.datetime.now()}] Raw Response From LLM: '{response.generations[0][0].text}'\n") # Write the raw response generated by the LLM