from langchain_core.callbacks import BaseCallbackHandler # Import base-class required to create a callback handler
from typing import Any, Dict, List # Import Type-Hints package
from langchain_core.outputs import LLMResult # Import class representing LLM response
import logging # Import Logging package


class CallBackHandler(BaseCallbackHandler): # Custom call-back handler that inherits from the imported base class
    def on_llm_start(self, serialized:Dict[str, Any], prompts:List[str], **kwargs:Any) -> Any: # Method/Hook triggered immediately before LLM starts executing
        final_prompt = prompts[0] # Retrieve final prompt passed to model
        logging.info(f"Prompt Sent to LLM -> {final_prompt}") # Log the final prompt

    def on_llm_end(self, response:LLMResult,  **kwargs:Any) -> Any: # Method/Hook triggered immediately after the LLM generates a response
        final_response = response.generations[0][0].text # Retrieve result generated by LLM
        logging.info(f"Final Response -> {final_response}") # Log the final response