name: Deploy Infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  # ==========================================
  # JOB 1: Plan the Infrastructure
  # ==========================================
  terraform-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Infrastructure

    env:
      TF_VAR_google_api_key: ${{ secrets.GOOGLE_API_KEY }}
      TF_VAR_pinecone_api_key: ${{ secrets.PINECONE_API_KEY }}
      TF_VAR_hugging_face_token: ${{ secrets.HUGGINGFACE_TOKEN }}
      TF_VAR_langchain_api_key: ${{ secrets.LANGCHAIN_API_KEY }}
      TF_VAR_google_oauth_client_id: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
      TF_VAR_google_oauth_client_secret: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        # We drop the -out=tfplan here because passing binary plan files 
        # between ephemeral GitHub runners is notoriously buggy.
        run: terraform plan 

  # ==========================================
  # JOB 2: Await Approval and Apply
  # ==========================================
  terraform-apply:
    needs: terraform-plan       # This tells GitHub to wait for the plan to finish
    environment: production     # This triggers the manual approval pause!
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Infrastructure
    env:
      TF_VAR_google_api_key: ${{ secrets.GOOGLE_API_KEY }}
      TF_VAR_pinecone_api_key: ${{ secrets.PINECONE_API_KEY }}
      TF_VAR_hugging_face_token: ${{ secrets.HUGGINGFACE_TOKEN }}
      TF_VAR_langchain_api_key: ${{ secrets.LANGCHAIN_API_KEY }}
      TF_VAR_google_oauth_client_id: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
      TF_VAR_google_oauth_client_secret: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Because this is a brand new runner, we must init again
      - name: Terraform Init
        run: terraform init

      - name: Force State Sync
        run: terraform import module.compute.google_identity_platform_config.auth_config projects/cliniclarity || true

      - name: Terraform Apply
        run: terraform apply -auto-approve
